version: '3'
services:
  app_web_devops:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
     - ":80"
    depends_on:
      - nginx
  
  nginx:
   build:
      context: .
      dockerfile: DockerfileNginx.DOCKERFILE
  
      
 