version: '3'
services:
  app_web_devops:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/home/node

  nginx_devops:
    build:
      context: .
      dockerfile: DockerfileNginx
    ports:
      - 3000:80
    volumes:
      - ./:/home/node
      - ./config/nginx/:/etc/nginx/conf.d/
    depends_on:
      - app_web_devops
