apiVersion: v1
clusters:
- name: "k8s-esgi-devops"
  cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM1ekNDQWMrZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJek1URXhOekl5TVRRek0xb1hEVE16TVRFeE56SXlNVFF6TTFvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTUh4CjJMK2xRZnUzaCtrajFTWFBzWjB3NWRSdm1TaE1jYXVHQzRJcXNCM3hkWi9uSUtFVHljdUxrNzZaL2FQd3RtbUcKQ1Iyc29BelQ1OXVVZmI5RVBnS2JPTTNKNCs1aG0wMFdRY0FZSUhvSE1VdDdya2VSR01UY3hYSU5YaUMwREhOaQpycUl2OEE4OCtCaFhmUGNnR1BIQTdTemNmYmZnTEpFdDdDSDd2TWxxWWgwQVBSVzRHUHROVTV0MkJKTmhnWERzCnUwZ0FIK1NZWjViQVRjaGNEeE1BRlVhdVVIWmpDVWZraDQraE9RSko1YVhFaWJaUFAvL1orWEVPc0NzN0w5Vk4KWjhyKzBqeGFBWlRTN1lWNTZ1cWhadldvKzZoQVFLZHkvMjg2Nm1aNEZITHJxei9qWW9XVDFKb1krcXR3S2FhQwptNS92R2NCS0dkOEd3WUkxUTVjQ0F3RUFBYU5DTUVBd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZCa1k3Q0tWaVRhMmJNallVUm9mM29Xc1A0ZFBNQTBHQ1NxR1NJYjMKRFFFQkN3VUFBNElCQVFBV0RsYkY0T2JhN3BkcXBwN3JhNkFNMXo3OTQrU2x2NkFNcnFEYm15bEd1ZFhzbTRkTApJbXpjYlo2Tm5oemFJM0dtVmdYNmZGQytCdzdFYmc3OW5Xd1dpS0ovZlZ5a21NWlhJNzhEbHNVdUMvb0tyT2pvCjdRVW0rU0ZoVGE0bW44dDRkKy9BZi9qSGwxU01UcWZSMmI3cGN2QzA5RmpPSEJwTms3WFI4aFhpRTVybnZtZGkKQjc4WWZFc096MGJrVkRIcmpFQnZuSlhVSTdQa2RsVmYycGFQS0drcUtmaW1kVnlodWZFV21MOEJCTXhNVzFUWApIa3RjR0d5a1ZEMnZTSHRtdnA4RzZjV3g5NVRTbVVlUEZyYTNTdHdpQWVMZ2ZMYWlHNnZzMURMZFBSTXFIQ2IzCmhSdUdqWWFUcjFXNkltaG1ncU5ZTndKcjJxTEFJOHFxS0hSTQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://8fde55f4-a49b-4e5b-acef-3600c332baa3.api.k8s.fr-par.scw.cloud:6443
contexts:
- name: admin@k8s-esgi-devops
  context:
    cluster: "k8s-esgi-devops"
    user: k8s-esgi-devops-admin
current-context: admin@k8s-esgi-devops
kind: Config
preferences: {}
users:
- name: k8s-esgi-devops-admin
  user:
    token: K8ygt0RhArBlpJ7QFX54c1OryZX3na9XaQWw95uNM69Pr9BOWXVspPnC